Import( '*' )

# environment
env.VariantDir( build_dir, '#', duplicate = 0 )
semver_env = env.Clone()

# sources
files = [ 'semver/semver.c' ]
files = [build_dir + f for f in files]

# project settings
if plat == 'Linux':
	semver_env['CCFLAGS'] += [ '-fPIC' ]
	semver_env['CFLAGS'] += [ '-std=c99' ]

# targets
result = semver_env.StaticLibrary( build_dir + 'libsemver', files )
Return( "result" )
