Import( '*' )

# environment
env.VariantDir(
	build_dir,
	'#',
	duplicate = 0
)
maxmind_env = env.Clone()

# sources
files = [
	'maxmind/maxminddb.c',
]
files = [build_dir + f for f in files]

# project settings
if realcc == 'gcc' or realcc == 'clang' and plat != 'Windows':
	maxmind_env['CCFLAGS'] += [
		'-fPIC',
	]
	maxmind_env['CPPPATH'] += [
	'#' + os.sep + 'maxmind'
]
# targets
result = maxmind_env.StaticLibrary(
	build_dir + 'libmaxmind',
	files
)
Return( "result" )
