Import( '*' )

# environment
env.VariantDir(
	build_dir,
	'#',
	duplicate = 0
)
json_env = env.Clone()

# sources
files = [
	'cJSON/cJSON.c',
]
files = [build_dir + f for f in files]

# targets
result = json_env.StaticLibrary(
	build_dir + 'libcJSON',
	files
)
Return( "result" )
