Import( '*' )

# environment
env.VariantDir(
	build_dir,
	'#',
	duplicate = 0
)
json_env = env.Clone()

# sources
files = [
	'cJSON/cJSON.c',
]
files = [build_dir + f for f in files]

# project settings
if ('gcc' in realcc or 'clang' in realcc) and plat != 'Windows':
	json_env['CCFLAGS'] += [
		'-fPIC',
		'-Wno-unsuffixed-float-constants',
		'-Wno-cast-qual',
	]

# targets
result = json_env.StaticLibrary(
	build_dir + 'libcJSON',
	files
)
Return( "result" )
